export const tiposPokemon = {
  normal: 'Normal',
  fire: 'Fogo',
  water: 'Água',
  electric: 'Elétrico',
  grass: 'Planta',
  ice: 'Gelo',
  fighting: 'Lutador',
  poison: 'Venenoso',
  ground: 'Terra',
  flying: 'Voador',
  psychic: 'Psíquico',
  bug: 'Inseto',
  rock: 'Pedra',
  ghost: 'Fantasma',
  dragon: 'Dragão',
  dark: 'Sombrio',
  steel: 'Aço',
  fairy: 'Fada'
};

export const estatisticasPokemon = {
  hp: 'HP',
  attack: 'Ataque',
  defense: 'Defesa',
  'special-attack': 'Ataque Especial',
  'special-defense': 'Defesa Especial',
  speed: 'Velocidade'
};

export const habilidadesPokemon = {
  'overgrow': 'Supercrescimento',
  'chlorophyll': 'Clorofila',
  'blaze': 'Chama',
  'solar-power': 'Poder Solar',
  'torrent': 'Torrente',
  'rain-dish': 'Prato de Chuva',
  'static': 'Estático',
  'lightning-rod': 'Para-Raios',
  'sand-veil': 'Véu de Areia',
  'sand-rush': 'Corrida de Areia',
  'run-away': 'Fugir',
  'guts': 'Determinação',
  'hustle': 'Esforço',
  'intimidate': 'Intimidação',
  'unnerve': 'Perturbar',
  'pressure': 'Pressão',
  'inner-focus': 'Foco Interior',
  'infiltrator': 'Infiltrante',
  'keen-eye': 'Olho Aguçado',
  'tangled-feet': 'Pés Emaranhados',
  'big-pecks': 'Bico Grande',
  'pickup': 'Pegar',
  'technician': 'Técnico',
  'unburden': 'Alívio',
  'mold-breaker': 'Quebra Moldes',
  'turboblaze': 'Turbulência',
  'teravolt': 'Teravolt',
  'multitype': 'Multitipo',
  'flower-gift': 'Presente de Flor',
  'bad-dreams': 'Pesadelos',
  'prankster': 'Travesso',
  'sand-force': 'Força de Areia',
  'iron-fist': 'Punho de Ferro',
  'mega-launcher': 'Mega Lançador',
  'aromaveil': 'Véu Aromático',
  'protean': 'Proteano',
  'fur-coat': 'Capa de Pele',
  'magician': 'Mágico',
  'bulletproof': 'À Prova de Balas',
  'competitive': 'Competitivo',
  'strong-jaw': 'Mandíbula Forte',
  'refrigerate': 'Refrigerar',
  'sweet-veil': 'Véu Doce',
  'stakeout': 'Vigilância',
  'water-compaction': 'Compactação de Água',
  'merciless': 'Implacável',
  'shields-down': 'Escudos Abaixados',
  'stamina': 'Resistência',
  'wimp-out': 'Covardia',
  'emergency-exit': 'Saída de Emergência',
  'water-bubble': 'Bolha de Água',
  'steelworker': 'Trabalhador de Aço',
  'battery': 'Bateria',
  'fluffy': 'Fofo',
  'dazzling': 'Deslumbrante',
  'soul-heart': 'Coração da Alma',
  'tangling-hair': 'Cabelo Emaranhado',
  'receiver': 'Receptor',
  'power-of-alchemy': 'Poder da Alquimia',
  'beast-boost': 'Impulso da Fera',
  'rks-system': 'Sistema RKS',
  'electric-surge': 'Surto Elétrico',
  'psychic-surge': 'Surto Psíquico',
  'misty-surge': 'Surto Nebuloso',
  'grassy-surge': 'Surto Gramíneo',
  'full-metal-body': 'Corpo Totalmente Metálico',
  'shadow-shield': 'Escudo Sombrio',
  'prism-armor': 'Armadura Prismática',
  'neuroforce': 'Neuroforça',
  'intrepid-sword': 'Espada Intrépida',
  'dauntless-shield': 'Escudo Destemido',
  'libero': 'Líbero',
  'ball-fetch': 'Buscar Bola',
  'cotton-down': 'Algodão',
  'propeller-tail': 'Cauda de Hélice',
  'mirror-armor': 'Armadura Espelhada',
  'gulp-missile': 'Engolir Míssil',
  'stalwart': 'Firme',
  'steam-engine': 'Motor a Vapor',
  'punk-rock': 'Punk Rock',
  'sand-spit': 'Cuspir Areia',
  'ice-scales': 'Escamas de Gelo',
  'ripen': 'Amadurecer',
  'ice-face': 'Cara de Gelo',
  'power-spot': 'Ponto de Poder',
  'mimicry': 'Mimetismo',
  'screen-cleaner': 'Limpeza de Tela',
  'steely-spirit': 'Espírito de Aço',
  'perish-body': 'Corpo Perecível',
  'wandering-spirit': 'Espírito Errante',
  'gorilla-tactics': 'Táticas de Gorila',
  'neutralizing-gas': 'Gás Neutralizante',
  'pastel-veil': 'Véu Pastel',
  'hunger-switch': 'Interruptor da Fome',
  'quick-draw': 'Desenho Rápido',
  'unseen-fist': 'Punho Invisível',
  'curious-medicine': 'Medicina Curiosa',
  'transistor': 'Transistor',
  'dragons-maw': 'Mandíbula do Dragão',
  'chilling-neigh': 'Relincho Gelado',
  'grim-neigh': 'Relincho Sombrio',
  'as-one': 'Como Um',
  'as-one-glastrier': 'Como Um - Glastrier',
  'as-one-spectrier': 'Como Um - Spectrier'
};

export function traduzirTipo(tipo) {
  return tiposPokemon[tipo] || tipo;
}

export function traduzirEstatistica(stat) {
  return estatisticasPokemon[stat] || stat.replace('-', ' ');
}

export function traduzirHabilidade(habilidade) {
  return habilidadesPokemon[habilidade] || habilidade.replace('-', ' ');
}
